### ISSUE TITLE
Support Google Http Client

### ISSUE THREAD

**Issue by blakesmith** [OpenFeign/feign#1053]
Hi feign friends!

We've been running our own Feign `Client` in production for the [google-http-java-client](https://github.com/googleapis/google-http-java-client) (Repository is here: https://github.com/sproutsocial/feign-google-http-client). It's pretty small, and has been quite stable. Would there be any interest in this code being mainlined into the main `feign` repo as another feign submodule?

Thanks!

**Comment by kdavisk6** [comment]
@blakesmith 

cc: @velo 

This looks like a great addition.  In order to bring this in, we will need to make the following changes:

1.  Change the license to Apache 2.0
2. Change the package to `feign.googleclient` (or something similar)
3. Future changes will update the copyright to include both Sprout Social and OpenFeign.

If you are ok with these changes, I don't see any reason not to bring it in.

**Comment by blakesmith** [comment]
Totally fine with all of those changes. I'm happy to do the work to fold this in, and send PRs - please let me know the best way to go about this! :-)

Thank you for feign, and all the great work!

**Comment by kdavisk6** [comment]
The easiest is for you to create a fork, add your module as a new folder in the main repo and submit a PR with the module included in the parent and the appropriate versions set up.  Let me know if you need any more help.

**Comment by blakesmith** [comment]
@kdavisk6 Sounds good. PR forthcoming.

**Comment by velo** [comment]
Agree with Kevin.
Send a PR our way and I would be happy to review it.

I kinda did already by looking at the original code and should be fine with the changes Kevin proposed.

I would also include a disclaimer on the original project pointing to be home.

**Comment by blakesmith** [comment]
PR is up here: https://github.com/OpenFeign/feign/pull/1057
