### ISSUE TITLE
QueryTemplate Bug in 10.x

### ISSUE THREAD

**Issue by zhangruican** [OpenFeign/feign#1064]
```java
RequestTemplate template = new RequestTemplate().query("url", "{url}").query("b", "{b}");
Map<String, String> vars = Maps.newHashMap();
vars.put("url", "http://www.baidu.com/?a=1&b=2");
vars.put("b", "3");
template = template.resolve(vars);
System.out.println(template.url());  // output /?url=http:%2F%2Fwww.baidu.com%2F%3Fa=1&b=2&b=3
```
should /?url=http:%2F%2Fwww.baidu.com%2F%3Fa=1%26b=2&b=3
QueryTemplate use Template.parseTemplate

**Comment by kdavisk6** [comment]
@zhangruican 

What exactly is the issue in the result?

**Comment by zhangruican** [comment]
an issue with URI template encoding ,  '&' encoding

**Comment by kdavisk6** [comment]
That is intentional.  Feign will consider the value for a template variable in its entirety when resolving the template.  It will also encode the entire value before substitution.  I suspect the output you are looking for is:

```
/?url=http:%2F%2Fwww.baidu.com%2F%3Fa=1%26b=2%26b=3
```

If that is the case, you will need to provide the complete value as `{ur}l`.

**Comment by kdavisk6** [comment]
Please see #1138 for background on this issue and a potential fix.
