### ISSUE TITLE
loggerLevel > NONE not working on partial request (206)

### ISSUE THREAD

**Issue by bananaspliff** [OpenFeign/feign#1134]
the bug appear only if you have a specific logger in DEBUG like this :

```java
@Component
public class FeignLogger extends Logger {

	@Override
	protected Response logAndRebufferResponse(String configKey, Level logLevel, Response response, long elapsedTime) {
		// NOOP
		return response;
	}

	@Override
	protected void log(String configKey, String format, Object... args) {
		// NOOP
	}

	@Bean
	public Level defaultFeignLogger() {
		return BASIC;
	}

}
```

```
DEBUG XXX.26 - exiting logAndRebufferResponse with result HTTP/1.1 206 Partial Content
content-type: application/json;charset=utf-8
server: Jetty(9.4.24.v20191120)
transfer-encoding: chunked
feign.Response$InputStreamBody@71ace013 .  
16:30:07.301 [main] DEBUG XXX.FeignLogger:63 - [XXX] <--- ERROR IOException: stream is closed (227ms)
```
works with Feign 10.1 and not working with Feign 10.4

**Comment by bananaspliff** [comment]
works with Feign 10.1 and not working with latest Feign 10.4

**Comment by kdavisk6** [comment]
This is because the logger you have implemented violates the `Logger` contract.  The method `logAndRebufferResponse` expects that the `Response` returns contains an `InputStream` that can be read again.  This is required since `logAndRebufferResponse` is called *before* the `Response` is processed.

Please refer to the default `Logger` implementation for an example.

**Comment by bananaspliff** [comment]
i write just a log, i don't use the inputStream of the Response. you can try with my example with noops.

**Comment by bananaspliff** [comment]
oh my bad !  there is a code that displays the whole object with aspect !
