### ISSUE TITLE
Question about @QueryMap behavior

### ISSUE THREAD

**Issue by Blackbaud-MikeLueders** [OpenFeign/feign#1151]
We recently upgraded from open feign 10.0.1 to 10.7.0 and noticed a difference in behavior of @QueryMap when dealing with null values.

Given the following client
```java
public interface DemoClient {
    @RequestMapping(path = "/test", method = RequestMethod.GET)
    String test(@QueryMap Map queryMap);
}
```

And the following invocation
```java
Map queryMap = new HashMap();
queryMap.put("key", null);
demoClient.test(queryMap)
```

The 10.0.1 client results in the following request
```
GET http://localhost:10000/test 
```
While the 10.7.0 client results in the following request
```
GET http://localhost:10000/test?key
```

Is this change in behavior intended/correct?

**Comment by kdavisk6** [comment]
This is intentional.  Query Maps are processed as literals, so all key/value combinations will be included on the query string.  This change was made to Query Map processing consistent with our URI Template processing and expansion.

If you want the previous behavior, remove any keys with `null` values from the Map before processing.

**Comment by Blackbaud-MikeLueders** [comment]
Makes sense, thanks for the explanation
