### ISSUE TITLE
How to configure the client to connect directly to the server without using a load balancer

### ISSUE THREAD

**Issue by xue8** [OpenFeign/feign#1154]
How to configure the client to connect directly to the server without using a load balancer.

**Comment by kdavisk6** [comment]
This is outside of Feign and really part of the Client you use.  From your issue it sounds like you are using Ribbon.  If you want to continue to use Ribbon, please read their documentation on how to avoid the client side load balancing.  Otherwise, switch to a different Client such as the Apache HTTP, OkHttp or the Google client.
