### ISSUE TITLE
Request.Body in 10.7.3 is API-incompatible with 10.7.2 and breaks downstream projects

### ISSUE THREAD

**Issue by fpavageau** [OpenFeign/feign#1163]
The refactoring in 75e569fb3f87b4f5e3a638dd65e90cc8a5adf8d1 removed `Request.Body.encoded()` (see https://github.com/OpenFeign/feign/commit/75e569fb3f87b4f5e3a638dd65e90cc8a5adf8d1#diff-1a38e5b4f4df73af6b31204e82e13a4b), which breaks [feign-form](https://github.com/OpenFeign/feign-form/blob/3.8.0/feign-form/src/main/java/feign/form/MultipartFormContentProcessor.java#L104) among other things.

As the method was not marked as deprecated, I don't think it should have been removed in a patch version.

Other methods that were removed without prior warning include:
- `Request.Body.expand()`
- `Request.Body.getVariables()`
- `Request.Body.bodyTemplate()`

**Comment by kdavisk6** [comment]
Short answer, these were internal methods that should have not been exposed as `public`.

Long answer
A number of changes made to address other issues made these methods inconsistent.  I apologize for removing them without marking them as deprecated.  I will restore `Body.encoded` for Spring compatibility.

`Body.expand`, `Body.getVariables` and `Body.bodyTemplate` were duplicates of `RequestTemplate.expand`, `RequestTemplate.getVariables`, and `RequestTemplate.bodyTemplate` respectively and were error prone since they were inconsistent with the logic in their `RequestTemplate` counterparts.  

If you have a specific use case where you are manually resolving or modifying the `BodyTemplate`, I would like to hear more about it.

I will release a patch release (10.7.4) immediately restoring `Request.Body.encoded`

**Comment by kdavisk6** [comment]
10.7.4 is now available on Central.

**Comment by velo** [comment]
@kdavisk6 maybe we should fold feign form into main repo...
