### ISSUE TITLE
Feign 10.9: deprecated "encoded=true" attribute on @Param ignored

### ISSUE THREAD

**Issue by datazuul** [OpenFeign/feign#1216]
I use a custom Expander returning e.g. String "pageNumber=0&pageSize=100".
When using it like this:
```
@RequestLine("GET /latest/webpages/{uuid}/children?{pageRequestParams}")
  List<Webpage> getChildren(
      @Param("uuid") UUID uuid,
      @Param(
              value = "pageRequestParams",
              expander = PageRequestToUrlParamsExpander.class,
              encoded = true)
          PageRequest pageRequest);
```
the returned String gets encoded to "pageNumber%3D0%26pageSize%3D100" and server does not recognize params anymore.

Seems "encoded=true" has no effect. Bug?
(even if it is deprecated it should work)

Expander-Signatures:
```
import feign.Param;

public class PageRequestToUrlParamsExpander implements Param.Expander {
  ...
  @Override
  public String expand(Object pageRequestObj) {
    String urlParams;
    ...
    return urlParams;
  }
}
```

**Comment by kdavisk6** [comment]
@datazuul 

This is intentional, however, I can see where this may not be clear.  Feign adheres to the [URI Template specification's Level 1 templates](https://tools.ietf.org/html/rfc6570#section-1.2), which require all reserved characters to be pct-encoded during expansion.

This rule is enforced _after_ a value has been expanded, to address numerous expansion encoding consistency issues that had been reported.  This change made the `encoded = true` escape hatch irrelevant and removed it's capability to change the result, hence it's deprecation.

With that said, your example is reasonable and an appropriate use case.  It will not be possible to restore the functionality provided by `encoded=true` without some considerable refactoring of our expansion process, but I do want to provide you with something workable in the near term, while I work on this.  In this very specific case, if it is at all possible to adjust the Feign Interface, I would recommend being explicit with the URL and the values:

```java
@RequestLine("GET /latest/webpages/{uuid}/children?pageNumber={pageNumber}&pageSize={pageSize}")
  List<Webpage> getChildren(
      @Param("uuid") UUID uuid,
      @Param("pageNumber") int pageNumber,
      @Param("pageSize")int pageSize);
```

If this is not possible, then downgrading Feign maybe your only option in the near term.

Thoughts?

**Comment by datazuul** [comment]
Thank you for your answer. As `@Param` expander is not applicable for expanding more than one param value, I create now a Map<String, Object> (flattening my POJO containing two sub-POJOs) before calling `@RequestLine` annotated method and passing this map as `@QueryParam`.

Example:
```
@RequestLine("GET /latest/webpages/{uuid}/children")
  PageResponse<Webpage> getChildren(@Param("uuid") UUID uuid, @QueryMap Map queryMap);
```

**Comment by kdavisk6** [comment]
Proposal for your suggestion created: #1312.  Let's continue the discussion on this feature there.
