### ISSUE TITLE
Our monitor system needs to know the origin restful url

### ISSUE THREAD

**Issue by varnson** [OpenFeign/feign#1242]
We are using openfeign with spring cloud.
For example, we have a feignclient:
@FeignClient
public interface User{
@RequestMapping("user/{id}")
public Object getUser(String id);
} 
Our monitor system needs to know how much times this url(user/{id}) was called.
But the parameter "id” was replaced with openFeign, such as /user/123, /user/456.
How can we get the origin url /user/{id}?  
Or should we modify the openFeign to add a request header to identify the origin url?

**Comment by velo** [comment]
How do you write to this monitor system?!

**Comment by varnson** [comment]
Just like requestinterceptor, get the url from request  and write to the monitor system.

**Comment by kdavisk6** [comment]
Without getting into too much regarding how to fix this on your monitoring system, _tldr; use regex matching instead of exact matching_, there is currently no way to obtain the URI Template from an interceptor.

The `RequestTemplate` provided to the interceptor is partially resolved and the URI Template is no longer available.  #873 has been opened and is for us to look into providing this capability.  I recommend adding your use cases to that issue.

**Comment by velo** [comment]
@varnson what if you use `feignTarget()` method on the `RequestTemplate`?

**Comment by velo** [comment]
One week without feedback. Think we can close.
