### ISSUE TITLE
why remove “/” when url end with “/”

### ISSUE THREAD

**Issue by yingziisme** [OpenFeign/feign#1256]
RequestTemplate.java 
```java
public RequestTemplate target(String target) {
    /* target can be empty */
    if (Util.isBlank(target)) {
      return this;
    }

    /* verify that the target contains the scheme, host and port */
    if (!UriUtils.isAbsolute(target)) {
      throw new IllegalArgumentException("target values must be absolute.");
    }
    if (target.endsWith("/")) {
      target = target.substring(0, target.length() - 1);
    }

    /* no query strings allowed */
    Matcher queryStringMatcher = QUERY_STRING_PATTERN.matcher(target);
    if (queryStringMatcher.find()) {
      /*
       * target has a query string, we need to make sure that they are recorded as queries
       */
      int queryStart = queryStringMatcher.start();
      this.extractQueryTemplates(target.substring(queryStart + 1), true);

      /* strip the query string */
      target = target.substring(0, queryStart);
    }
    this.target = target;
    return this;
  }
```

when url end with "/", it removes "/"
i want to know why do this
in our project, we use a dynamic configuration to the url which is from thirdpart
sometimes the url they provide is end with "/"

**Comment by kdavisk6** [comment]
That's because this function is responsible for creating the scheme and authority parts of the URI only.  The trailing slash is considered part of the path and is the responsibility of the URI Template defined in `@RequestLine`, so it is ignored here.  There is special handling for Query Strings given their special requirements when present on a URI template.

We need to divide up the target this way to ensure that we are processing each part of the URI per the rules outlined in the URI Template Specification: https://tools.ietf.org/html/rfc6570
