### ISSUE TITLE
FieldQueryMapEncoder may not be thread-safe

### ISSUE THREAD

**Issue by 542803359** [OpenFeign/feign#1257]
![image](https://user-images.githubusercontent.com/46744543/88133164-f9771f80-cc13-11ea-93bc-0378f476c409.png)

建议使用ConcurrentHashMap 
eg:private final Map<Class<?>, ObjectParamMetadata> classToMetadata =
            new ConcurrentHashMap<Class<?>, ObjectParamMetadata>();

![image](https://user-images.githubusercontent.com/46744543/88133085-d0568f00-cc13-11ea-9a69-8a78e740e830.png)
此处s是否可以添加 synchronized ()修饰符,当然,使用ConcurrentHashMap就没有必要了

**Comment by velo** [comment]
Vixi Mano, assim fica complicado o bagulho, tá ligado.

**Comment by kdavisk6** [comment]
For the English speakers here, the original request is asking why this loop, which is present in `FieldMapQueryEncoder` is not synchronized, implying the thread safety of the serialization is suspect.  It is true that the way the `FieldMapQueryEncoder` is currently written, access to the underlying cached map is not thread-safe, however since access to the map is not "leaked", it is still fine to use.

To correct this, we would need to apply atomic get-then-set semantics and switch the cache to a `ConcurrentHashMap`

**Comment by FedericoAlvarez** [comment]
Hello there, 
i would like to help on this as part as the hackoctoberfest!
Any extra information to start?

Cheers,

**Comment by FedericoAlvarez** [comment]
I've created this pr please let me know if is ok :)
https://github.com/OpenFeign/feign/pull/1290
