### ISSUE TITLE
Feign11 package on Maven Repository?

### ISSUE THREAD

**Issue by Klaboe** [OpenFeign/feign#1263]
According to the Maven repository

https://mvnrepository.com/artifact/io.github.openfeign/feign-core/11.0

version 11.0 was released in april; but i can find nothing about it here. Does anyone know where this came from?

And what is the status of 11.0?

**Comment by ChristianCiach** [comment]
See here: https://github.com/OpenFeign/feign/issues/1218

11.0 has been released by accident. This is especially bad, since, according to maven central, more people already depend on 11.0 than on previous versions.

What about 10.11? Has this been released on accident, too? There are no release notes for 10.11.

**Comment by kdavisk6** [comment]
There is nothing we can do about this.  Once deployed to Maven Central, it's there forever.  We will continue to remind folks to not use it.

**Comment by Klaboe** [comment]
Thanks for the replies. Then we all eagerly await 11.0.REAL :)
