### ISSUE TITLE
Why is there a release of io.github.openfeign modules labeled 11.0.0?

### ISSUE THREAD

**Issue by rhanton** [OpenFeign/feign#1310]
I'm worried about the legitimacy of the 11.0.0. build showing in the MVN central repositories that was created in April 2020, as there is no release from this project labeled 11.0.0 and it appears that there isn't even a milestone release of 11.x yet. My concern is for any security issues this may cause for projects using tools like dependabot or snyk to automatically keep dependencies up-to-date if it was not built by the maintainers of this project via normal release processes.

Maybe it is legit and I'm worried for no reason, but this is concerning.

See: https://mvnrepository.com/artifact/io.github.openfeign/feign-core/11.0

**Comment by kdavisk6** [comment]
There are other issues here that explain this more fully, but the short story is we had an issue with our CI system and it released the wrong version to Maven Central.  Since Central doesn't support removing of artifacts once published, they use a stage then release system to prevent this, but we unknowingly had the "auto release" flag set, we are stuck with that version.

**Comment by kdavisk6** [comment]
Corrected
