### ISSUE TITLE
URI template encoding Bug in 10.x

### ISSUE THREAD

**Issue by R-anybbo** [OpenFeign/feign#1315]
Hi.

```
Get http://localhost:8080/user/v1?userId=2020051417013580630000001&123

userId='2020051417013580630000001&123'
```

There is a '&' symbol in the parameter causing segmentation error.

 
![image](https://user-images.githubusercontent.com/13247139/100038437-e765f180-2e3e-11eb-88b5-274a9f8a6b3b.png)

![image](https://user-images.githubusercontent.com/13247139/100042309-28153900-2e46-11eb-97e7-031c0b1fd205.png)

![image](https://user-images.githubusercontent.com/13247139/100042344-37948200-2e46-11eb-8359-41e41a3cb128.png)

The actual received value is   '2020051417013580630000001'
![image](https://user-images.githubusercontent.com/13247139/100042240-0451f300-2e46-11eb-850f-cea007cea0b2.png)

**Comment by R-anybbo** [comment]
![image](https://user-images.githubusercontent.com/13247139/100042309-28153900-2e46-11eb-97e7-031c0b1fd205.png)

![image](https://user-images.githubusercontent.com/13247139/100042344-37948200-2e46-11eb-8359-41e41a3cb128.png)


The actual received value is   '2020051417013580630000001'
![image](https://user-images.githubusercontent.com/13247139/100042240-0451f300-2e46-11eb-850f-cea007cea0b2.png)

**Comment by kdavisk6** [comment]
@R-anybbo this is intentional.  According to the URI Template specification any delimiter values in expressions must be pct-encoded in order to be honored.  My suggestion is to replace the `&` with `%26`.

For reference: [RFC 6578 - URI Template: Section 1.5](https://tools.ietf.org/html/rfc6570#section-1.5)

**Comment by dalaoyang** [comment]
Has the problem been solved?

@R-anybbo 

`URLEncoder.encode(userId, "UTF-8")`

**Comment by R-anybbo** [comment]
> Has the problem been solved?
> 
> @R-anybbo
> 
> `URLEncoder.encode(userId, "UTF-8")`

I am using this method now, thank you.

**Comment by kdavisk6** [comment]
> Do we need to do it? 

Simply put, yes.  I recommend you look over the RFC referenced for the background.

And yes `URLEncoder` can help, but be careful when using it.  It's not designed to perform Percent Encoding, but to handle `application/x-www-form-urlencoded` values only, which are not the same as Percent Encoding.

Some great reading on the subject

* https://www.talisman.org/~erlkonig/misc/lunatech%5Ewhat-every-webdev-must-know-about-url-encoding/
* https://www.proofbyexample.com/url-and-uri-encoding-in-java.html

Since you've found your solution, I'm going to close this issue.
