### ISSUE TITLE
Cannot customize how body templates resolve Iterable parameters

### ISSUE THREAD

**Issue by guch-gh** [OpenFeign/feign#1316]
My needs are:
Through the user-defined expander, the parameters are converted to JSON format and filled into the body template. If it is an Iterable parameter, it should be converted to JsonArray.

However in `feign.ReflectiveFeign.BuildTemplateByResolvingArgs#expandElements` Method, if parameter is `Iterable`, then `Expander` is not called on the original `Iterable` parameter, it's the elements. After expand, the parameter becomes `List`. Finally, in the `feign.template.Expressions.Simpleexpression#expand` method, the elements in the `List` are join with `;` . The logic in the middle cannot be modified to make it a JsonArray.

A workaround is uses the `RequestIntercepto`r to make the final modification to the `body`. However, it requires additional performance overhead to escape other parts of the `body`.

I wonder if the expander interface should be like this：
```
    interface Expander {

        /**
         * Expands the value into a string. Does not accept or return null.
         */
        String expand(Object value);
        
        default boolean acceptOriginalIterable() {
            return false;
        }
    }
```
In this way, I can write an `Expander` with `acceptOriginalIterable` is true to accept the original Iterable parameter and convert is to json array.

**Comment by kdavisk6** [comment]
@guch-gh 

This is intentional.  Per the URI Template Specification (Section 3.2.1)

> For a variable that is a list of values, expansion depends on both
   the expression type and the presence of an explode modifier.  If
   there is no explode modifier, the expansion consists of a comma-
   separated concatenation of the defined member string values.  If
   there is an explode modifier and the expression type expands named
   parameters (";", "?", or "&"), then the list is expanded as if it
   were an associative array in which each member value is paired with
   the list's varname.  Otherwise, the value will be expanded as if it
   were a list of separate variable values, each value separated by the
   expression type's associated separator as defined by the table above.

```
     Example Template     Expansion

       {count}            one,two,three
       {count*}           one,two,three
       {/count}           /one,two,three
       {/count*}          /one/two/three
       {;count}           ;count=one,two,three
       {;count*}          ;count=one;count=two;count=three
       {?count}           ?count=one,two,three
       {?count*}          ?count=one&count=two&count=three
       {&count*}          &count=one&count=two&count=three
```

Following this guidance, lists of values used to expand an expression within a template are expanded one by one.  We apply any custom expanders to the individual values in the list, not the entire list.  For example, given the following template:

```
https://api.example.com?count={count}
```

Where `count` is a `List<String>` containing the values `one, two, three`, the resulting uri would be:

```
https://api.example.com?count=one,two,three
```

Our support for custom `Expander` instances work on the individual values in the list.  The reason for this is because of the specification above.  Higher level templates define how the items in the list should be expanded and this is how we can remain compliant.

In your particular situation, I think that you have out grown the capabilities of a the `BodyTemplate`.  I recommend that you consider using a custom `Encoder` instead.  This will give you the ability to control the entire request body and add any specific custom logic you want.  `Encoder` instances have full access to the `RequestTemplate` as well.

You would go from this:

```java
interface LoginClient {

  @RequestLine("POST /")
  @Headers("Content-Type: application/json")
  // json curly braces must be escaped!
  @Body("%7B\"user_name\": \"{user_name}\", \"password\": \"{password}\"%7D")
  void json(@Param("user_name") String user, @Param("password") String password);
}
```

To this:

```java
interface LoginClient {

  // Credentials contains the parameters needed
  @RequestLine("POST /")
  @Headers("Content-Type: application/json")
  void json(@Body Credentials credentials);
}

// a custom encoder will need to be registered to turn Credentials into a JSON object
```

**Comment by guch-gh** [comment]
@kdavisk6 
Thank you for your reply.

```
interface LoginClient {

  @RequestLine("POST /")
  @Headers("Content-Type: application/json")
  // json curly braces must be escaped!
  @Body("%7B\"user_name\": \"{user_name}\", \"password\": \"{password}\"%7D")
  void json(@Param("user_name") String user, @Param("password") String password);
}
```
Just like this example，I want to put multiple parameters into the body and use the jsonobject format. Write json in `@Body` annotation seems not very convenient, and there is still the problem of passing `Iteratable`.

So I'm trying to write a custom Method Parameter annotation and processor, put the parameter name in the body template, and now this way can't work.

I can understand why iteratable is expanded in the URL template and `formurlencoded` body  template.
But this leads to the limitation of the body's template usage. expect some more flexible ways.

**Comment by kdavisk6** [comment]
@guch-gh 

I understand your situation and can see why you are frustrated.  However, Feign does not support multiple body parameters intentionally.  Also, again, the use of `@Body` with a template is meant for extremely simple situations and static values.  It does not support map and iterable values.

Given your desire to use `Iterable` parameter values, I recommend again, that you consider creating an object that represents your request body and using one of our existing `Encoder` implementations, such as the ones that use Jackson or GSON.  This will allow you to use `Map`, `Iterable` and static values appropriately.  If you need examples on how to achieve this, I recommend looking on Stack Overflow.

To get you started, here is a great example that uses GSON that achieves a similar result to what you are asking for:

[Intro to Feign | Baeldung](https://www.baeldung.com/intro-to-feign)

**Comment by guch-gh** [comment]
> Feign does not support multiple body parameters intentionally

That sounds convincing. I will try. thank you.
