### ISSUE TITLE
Request cookies exist for special characters, resulting in an error

### ISSUE THREAD

**Issue by jiaqing250** [OpenFeign/feign#1379]
When the cookie

userKindergarten={"user":{"authorities":"","access":["00002"]},"access_token":"res.model.token","token_type":" res.model.token_type"} 

feign Client , To invoke an error

java.util.regex.PatternSyntaxException: Illegal repetition
{"authorities"

**Comment by kdavisk6** [comment]
This question is better suited for Stack Overflow.  Please ask your question there and tag it with `feign`. 

The issue here is that your cookie is JSON.  Header values that are JSON or contain braces, must be pct-encoded to be accepted, as they clash with URI template expressions.  You'll need to build the header value directly and not using a literal.
