### ISSUE TITLE
IllegalState Body parameters cannot be used with form parameters.

### ISSUE THREAD

**Issue by Abhay-AKM** [OpenFeign/feign#1770]
`@Headers({"Content-Type: application/json"})
public interface InquiryApi {

    @RequestLine("POST /inquiry/travelerInquiry")
    @Body("{inquiryRequest}")
    InquiryResponse Inquiry(InquiryRequest inquiryRequest,
                                    @Param("id1") Optional<UUID> id1,
                                    @Param("language") Optional<String> language);
}`

Can you please tell why I am getting this error?
Thanks

**Comment by kdavisk6** [comment]
Questions like this are more appropriate for [Stack Overflow](https://stackoverflow.com/questions/tagged/feign).  Issues in this repository are for bug fixes and feature requests for the project. 

However, the error message does indicate where the problem is.  You cannot combine `@Param` and `@Body`.  Check our README for more documentation on how to set up the Annotations.
