### ISSUE TITLE
Method threw 'java.lang.IllegalStateException' exception. Cannot evaluate feign.RequestTemplate.toString()

### ISSUE THREAD

**Issue by mrxlh** [OpenFeign/feign#2089]
![image](https://github.com/OpenFeign/feign/assets/18496312/f3946e2e-a6fc-464d-ae73-fcb15350105c)

**Comment by Tantrax007** [comment]
Yep, I have the exact same problem, in this case with the next FeignClient definition:
```java
@FeignClient(
    value = "keycloakClient",
    url = "${keycloak.security.baseurl}",
    configuration = KeycloakExtClientConfiguration.class)
public interface KeycloakExternalClient {
  // Login de la aplicación
  @PostMapping(
      value = "realms/{realmName}/protocol/openid-connect/token",
      consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE)
  SessionTokensDTO login(
      @PathVariable String realmName, @RequestBody KeycloakAuthCredentials credentials);
}
```
The `KeycloakAuthCredentials` it's just a simple record with the data needed for login:
```java
public record KeycloakAuthCredentials(
    String client_id, String username, String password, String grant_type) {}
```

I noticed this fails when getting `[400 Bad Request] during [POST] to [http://localhost:8070/realms/SITEC/protocol/openid-connect/token] [KeycloakExternalClient#login(String,KeycloakAuthCredentials)]: [{"error":"invalid_request","error_description":"Missing form parameter: grant_type"}]'` after performing the request.

For now I couldn't found any further information, what I'm sure about is that it's not related with the use of Records instead of regular classes as I transformed it into a regular final one with AllArgsConstructor and Getters and still fails in the exact same point.
