### ISSUE TITLE
Support multipart/form-data by using Apache HTTP client

### ISSUE THREAD

**Issue by wanghongfei** [OpenFeign/feign#455]
Feign doesn't support `multipart/form-data` which Apache HTTP client does. The `httpclient` module provides Feign with the ability to plug Apache HTTP client in. So in theory Feign should support `multipart/form-data` as well.  How to let feign use Apache HTTP Client to send `multipart/form-data` request?

**Comment by tjuchniewicz** [comment]
I use this extension: https://github.com/xxlabaza/feign-form

There is a plan to merge this extension into Feign: https://github.com/OpenFeign/feign/issues/389

**Comment by wanghongfei** [comment]
I quickly browsed source code of the `MultipartEncodedDataProcessor` class of the project you mentioned. I found that it reads all bytes to memory then write them to request body once. This isn't the best way to use `multipart/form-data`. It should read one block of bytes  and send it to server one by one.
@tjuchniewicz

**Comment by tjuchniewicz** [comment]
You are right. This is current limitation of this module. Please create new issue in https://github.com/xxlabaza/feign-form.

**Comment by wanghongfei** [comment]
Maybe it's Feign's design that brings this limitation. Feign does not support streaming

**Comment by tjuchniewicz** [comment]
I believe that it can be supported by feign-form.

**Comment by tjuchniewicz** [comment]
@wanghongfei You were right. This is limitation of Feign. feign-form uses [`RequestTemplate body(byte[] bodyData, Charset charset)`](https://github.com/OpenFeign/feign/blob/968f35f1da60a12ae1ef5b7e2c14803882ce6bef/core/src/main/java/feign/RequestTemplate.java#L484) to encode request. I don't see any streaming version of this method.

**Comment by wanghongfei** [comment]
I found the following code in `ApacheHttpClient.java`:
```
//request body
    if (request.body() != null) {
      HttpEntity entity = null;
      if (request.charset() != null) {
        ContentType contentType = getContentType(request);
        String content = new String(request.body(), request.charset());
        entity = new StringEntity(content, contentType);
      } else {
        entity = new ByteArrayEntity(request.body());
      } // can we add: entity = new MultipartRequestEntity() ?

      requestBuilder.setEntity(entity);
    }
```
We can add another `else` branch that create `MultipartRequestEntity` object then assign it to `entity` variable. In this way we can make full use of Apache Http Client's multipart feature.

**Comment by bilak** [comment]
Hi is anybody working on this issue?
I was looking at implementations of Apache and Okhttp clients. 

in Apache [4.5.x]:   
--[ContentBody](https://github.com/apache/httpclient/blob/4.5.x/httpmime/src/main/java/org/apache/http/entity/mime/content/ContentBody.java)
---[AbstractContentBody](https://github.com/apache/httpclient/blob/4.5.x/httpmime/src/main/java/org/apache/http/entity/mime/content/AbstractContentBody.java)
----[ByteArrayBody](https://github.com/apache/httpclient/blob/4.5.x/httpmime/src/main/java/org/apache/http/entity/mime/content/ByteArrayBody.java)
----[FileBody](https://github.com/apache/httpclient/blob/4.5.x/httpmime/src/main/java/org/apache/http/entity/mime/content/FileBody.java)
----[InputStreamBody](https://github.com/apache/httpclient/blob/4.5.x/httpmime/src/main/java/org/apache/http/entity/mime/content/InputStreamBody.java)
----[StringBody](https://github.com/apache/httpclient/blob/4.5.x/httpmime/src/main/java/org/apache/http/entity/mime/content/StringBody.java)
for multipart:
--[AbstractMultipartForm](https://github.com/apache/httpclient/blob/4.5.x/httpmime/src/main/java/org/apache/http/entity/mime/AbstractMultipartForm.java)
--[FormBodyPart](https://github.com/apache/httpclient/blob/4.5.x/httpmime/src/main/java/org/apache/http/entity/mime/FormBodyPart.java)
--[FormBodyPartBuilder](https://github.com/apache/httpclient/blob/4.5.x/httpmime/src/main/java/org/apache/http/entity/mime/FormBodyPartBuilder.java)
--[MultipartEntityBuilder](https://github.com/apache/httpclient/blob/4.5.x/httpmime/src/main/java/org/apache/http/entity/mime/MultipartEntityBuilder.java)


in Okhttp:
--[RequestBody](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/RequestBody.java)
for multipart:
---[FormBody](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/FormBody.java)
---[MultipartBody](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/MultipartBody.java)

It would be nice to have instead of `body[]` in [Request](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/Request.java#L42) something like `Request.Body`. For this maybe [Body](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/Response.java#L255) interface could be reused (and moved out of Response class). Then there could exists implementations like `InputStreamBody`, `MultiPartBody`, `FormBody` and instead of working with `byte[]` it would be possible to work with nio streams and request body headers simpler. Also current implementation could be wrapped in ?`InputStreamBody`?

This will lead to lot of changes on request/requesttemplate APIs. I would like to look at that, because I need to get multipart support in application and currently this is very difficult using `byte[]`, but someone could give me a support with this (mainly with analysis what should be changed on which places).

**Comment by kdavisk6** [comment]
I think that you may want to open this issue against https://github.com/OpenFeign/feign-form.

**Comment by kdavisk6** [comment]
Support for MultiPart form data is part of Feign Form.
