### ISSUE TITLE
Need to extend JAXRSContract

### ISSUE THREAD

**Issue by MastaP** [OpenFeign/feign#558]
Hi,

Is there a particular reason for JAXRSContract class being final? One of our service APIs has an endpoint that returns CompletableFuture and JAXRSContract does not allow extending it for adding the support. In our other consumers of that endpoint implemented with Spring Boot we extend SpringMvcContract and it works like a charm.
Moreover, JAXRSContract has most of its methods with `protected` modifier, it doesn't make much sense if the class is itself final.

**Comment by adriancole** [comment]
the methods marked protected are because they are overriding or
implementing protected methods, right?

All types in feign are final unless specifically designed for being
overridable.

**Comment by adriancole** [comment]
PS is it normal for  JAXRS version 1 to return completable future? If this
is something more related to jaxrs-2 probably better for other threads on
that topic.

**Comment by MastaP** [comment]
Well, cannot say it's related to a particular version of JAXRS. We have a Boot service with an API interface `CompletableFuture<Data> getData()`. It had Spring's `@RequestMapping` annotation which worked fine for all other consumers on Boot. But now we need to use that endpoint in a service with no Spring and if we import that API module, it drags too much Spring-related stuff along which is not needed. Thus we added an JAXRS-based annotations to the endpoint without removing CompletableFuture.
Of course we can copy/paste JAXRSContract into our codebase and add support but I would be more natural just extend the class.

**Comment by adriancole** [comment]
Why dont you use feign annotations instead? It is more likely to be
supported that way. Ex feign-java8 could have a contract for this.

**Comment by MastaP** [comment]
Well, assume the provider API is fixed (having JAXRS annotations) and we just need to create a Feign client using that interface. I do not see any particular reason why the contract class cannot be extensible.

**Comment by adriancole** [comment]
when people extend things that aren't designed to be extended, odd bugs
happen, then they ask for support. That or things that are now extendable
are lock-in point for any future work. There is more on this in
effective-java, which is I think mentioned in the HACKING file.

In general, it is better to ask for what you need vs a specific way to
accomplish it. I do find it strange that you are moving to JAX-RS from
spring as a way out of lock-in considering JAX-RS interfaces were not
designed for use on the client anyway. I mentioned an alternative which is
to use the base Feign thing and redirect this to feign-java8.

If that's not ok with you, then this will just have to wait until it gets
more popular.

**Comment by Villane** [comment]
Hi, I'm on the same team with Pavel, I'll try to sum it up in my words:

We are already using Spring Boot on some services and Jersey (JAX-RS) for others. We were using Feign in most cases for the client-side (both in tests and for inter-service requests). But it turned out that in some services we couldn't use Feign's SpringContract because bringing in the whole Spring MVC and others as dependencies conflicted with other dependencies in the same project.

Now using JAX-RS annotations instead for the interface part seemed like a good idea, because there is only one jar with annotations to depend on - a client of such a service with JAXRSContract doesn't now need to have the whole Spring MVC on class path. Since JAXRSContract is a built-in Feign class I find it a bit strange to hear you arguing that this was never intended for client side - it's a use case you already support.

Since we already are using these interfaces in non-standard/non-intended way however, we have some more weirdness in that we use a base interface for both the SpringMVC controller interface and the one described with JAX-RS annotations. This seems like one of the most type-safe ways to do it. The MVC controller however returns CompletableFuture for async purposes, and thus our JAX-RS interface also uses that return type and this to the JAX-RS annotations and I think it's an entirely valid extension for the non-intended-use-case-of-JAX-RS that is already implemented in Feign. For comparison, SpringMvcContract is extensible - why such disparity?

Why we wouldn't use Feign annotations instead - well, JAX-RS seems a bit more client-neutral, although at the moment we do not use any other clients than Feign.

**Comment by adriancole** [comment]
you two seem to be going at great lengths to avoid using an alternative
suggestion to get the same thing accomplished. Let me know when you are
open to it. Having added Jax-Rs myself, I know why it was added and it was
mostly a mistake. There's no portability with other clients using Jax-RS,
so it is a very sincere feign. If you can find others that really want to
do this go ahead.

If you are willing to try a different route, like I've suggested a few
times, ping back.

**Comment by MastaP** [comment]
Ok, you can close the issue. In case anyone else is interested, our solution is as follows:
```
public class CompletableFutureContract implements Contract {

  private final Contract underlying;

  public CompletableFutureContract(Contract underlying) {
    this.underlying = underlying;
  }

  @Override
  public List<MethodMetadata> parseAndValidatateMetadata(Class<?> targetType) {
    List<MethodMetadata> metadatas = underlying.parseAndValidatateMetadata(targetType);

    for (MethodMetadata metadata : metadatas) {
      Type type = metadata.returnType();

      if (type instanceof ParameterizedType && ((ParameterizedType) type).getRawType().equals(CompletableFuture.class)) {
        metadata.returnType(resolveLastTypeParameter(type, CompletableFuture.class));
      }
    }

    return metadatas;
  }

}
```
passing it to the client builder 
`Feign.builder().contract(new CompletableFutureContract(new JAXRSContract()))`
