### ISSUE TITLE
MicroService Specific timeout value

### ISSUE THREAD

**Issue by remesh22** [OpenFeign/feign#580]
Hi,
I am using Feign+ Hystrix and API Gateway Pattern.
From the Gateway i am accessing MicroService A and MicroService B. I want to set the timeout value for Service A as 10 seconds.There is no mechanism to set the time out value for a particular MicroService.
I am listing down all the endpoints in my MicroserviceA as below:
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:  10000
        timeout:
          enabled: true
    SERVICEA#test1(String):
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:  5000
    SERVICEA#test2(String):
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:  5000

I have 50 endpoints in SERVICEA, i don't want to list all the endpoints in the properties/yml file.
Is there a mechanism to set MicroService specific timeout as below?
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:  10000
        timeout:
          enabled: true
    SERVICEA:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:  5000

**Comment by adriancole** [comment]
If you want to make different policies per api wrt timeouts, you can
either make separate feign instances with a client that has the
corresponding timeouts assigned, or may dispatching client which has
timeouts mapped by service. The client is the place to do this

On 11 Aug 2017 7:04 am, "remesh22" <notifications@github.com> wrote:

Hi,
I am using Feign+ Hystrix and API Gateway Pattern.
From the Gateway i am accessing MicroService A and MicroService B. I want
to set the timeout value for Service A as 10 seconds.There is no mechanism
to set the time out value for a particular MicroService.
I am listing down all the endpoints in my MicroserviceA as below:
hystrix:
command:
default:
execution:
isolation:
thread:
timeoutInMilliseconds: 10000
timeout:
enabled: true
SERVICEA#test1(String):
execution:
isolation:
thread:
timeoutInMilliseconds: 5000
SERVICEA#test2(String):
execution:
isolation:
thread:
timeoutInMilliseconds: 5000

I have 50 endpoints in SERVICEA, i don't want to list all the endpoints in
the properties/yml file.
Is there a mechanism to set MicroService specific timeout as below?
hystrix:
command:
default:
execution:
isolation:
thread:
timeoutInMilliseconds: 10000
timeout:
enabled: true
SERVICEA:
execution:
isolation:
thread:
timeoutInMilliseconds: 5000

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenFeign/feign/issues/580>, or mute the thread
