### ISSUE TITLE
Question Decoding Exceptions

### ISSUE THREAD

**Issue by liangGTY** [OpenFeign/feign#725]
Whether it should throw an exception directly when decoding is not wrapped with FeignException. For example, when used with hystrix, HystrixBadRequestException may be thrown without triggering a blow. Because some interfaces have an http status of 200, but the response is badRequest
![image](https://user-images.githubusercontent.com/18502949/41962799-8cfaa26c-7a28-11e8-9343-ebccfde8812e.png)

**Comment by kdavisk6** [comment]
If I understand your question, you are unsure if Feign should consider changing `DecodeException` handling.  At the moment, `DecodeException` is a `RuntimeException` and used to indicate that `Feign` was not able to convert the response data into the outgoing type.  This should be considered a stop the world problem and is implemented as such.

While it may not be a true `400 - Bad Request`, it is a request where the response is not quite what was expected and cannot be processed.  This is an exception that cannot and should not trigger a retry, which is why you can't handle it with an `ErrorDecoder`.  It's also something that breaks the `Contract` defined by the `Feign` interface, which is also considered a FATAL exception.  Given these reasons, a decode failure should be exposed directly and cause a throw.

Now with that said, the actual decoding is done by the registered `Decoder`.  If you need more control over this process, I recommend extending one of the existing `Decoder` implementations or creating one of you own.  That way, if you do not want a `DecoderException` thrown, write your own `decode` method to do so.  However, doing so may obscure errors in other parts of your application or api services.  YMMV.

**Comment by xiaomu1095** [comment]
I create one of `decoder` in configuration ,Feign configuration does not be annotated with `@Configuration`, and I have two configurations without `@Configuration`, But I can find my decoder in Linux env where Windows not, I don't know why.Can you give some suggestions? @kdavisk6

**Comment by kdavisk6** [comment]
@xiaomu1095 your question appears to be related to Spring and OpenFeign.  May I suggest that you ask this question on StackOverflow and tag it with Spring Cloud OpenFeign.  That will direct your question to the right people.

**Comment by liangGTY** [comment]
@kdavisk6 Actually, I want to throw my custom DecodeException.
```java
    try {
      return decoder.decode(response, metadata.returnType());
    } catch (FeignException e) {
      throw e;
    } catch (RuntimeException e) {
      throw new DecodeException(e.getMessage(), e);
    }
```
But here it is turned into a feign.codec.DecodeException

**Comment by kdavisk6** [comment]
That is currently not possible.  Decoding is not part of the Error Decoder path.

**Comment by kdavisk6** [comment]
I'm going to close this issue and recommend that questions like this be made on [Stack Overflow](https://stackoverflow.com/questions/tagged/feign), allowing more users to help you.
