### ISSUE TITLE
upload file multiple Content-Type has bad value

### ISSUE THREAD

**Issue by SirMin** [OpenFeign/feign#866]
#797  bug still exists
if  the method for the interface has @consumes, the @Consumes value append to the header, the header like 'multipart/form-data, multipart/form-data; charset=UTF-8; boundary=167d63cbb29'
```
if (!values.iterator().hasNext()) {
      /* empty value, clear the existing values */
      this.headers.remove(name);
      return this;
  }
```

Since the values above have values, the value of the header is not cleared, and if values and header has same value, The final result is as follows 'multipart/form-data, multipart/form-data; charset=UTF-8; boundary=167d63cbb29'

**Comment by SirMin** [comment]
If the added header contains the current value, I want to ignore the RequestTemplate header value,like this
`
Set<String> headerValues = values1.stream().filter(Util::isNotBlank)
        .filter(s -> !StreamSupport.stream(values.spliterator(), false)
            .anyMatch(s1 -> s1.contains(s)))
        .collect(Collectors.toSet());
    headerValues.addAll(StreamSupport.stream(values.spliterator(), false)
        .filter(Util::isNotBlank)
        .collect(Collectors.toSet()));
`

**Comment by kdavisk6** [comment]
Can you please provide an example of your Feign builder and interface along with the Feign version you are using?

**Comment by SirMin** [comment]
I'm using a component of the spring cloud,spring-cloud-starter-openfeign, feign version is 10.1.0, 
interface is this
```
@FeignClient("service1")
public interface TestApi {
    @GetMapping("/test")
    String test();

    @PostMapping(value = "uploadFile", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    String upload(@RequestPart("file") MultipartFile multipartFile) throws IOException;
}
```
and i find the reason is the HeadTemplate.append 
```
public static HeaderTemplate append(HeaderTemplate headerTemplate, Iterable<String> values) {
    Set<String> headerValues = new LinkedHashSet<>(headerTemplate.getValues());
    headerValues.addAll(StreamSupport.stream(values.spliterator(), false)
        .filter(Util::isNotBlank)
        .collect(Collectors.toSet()));
    return create(headerTemplate.getName(), headerValues);
  }
```
headerTemplate ready has Content-type, added another one.
I use a simple method to solve this problem
```
public static HeaderTemplate append(HeaderTemplate headerTemplate, Iterable<String> values) {
		//remove values exists
        Set<String> headerValues = headerTemplate.getValues().stream().filter(Util::isNotBlank)
        .filter(s -> !StreamSupport.stream(values.spliterator(), false)
                .filter(Util::isNotBlank)
            .anyMatch(s1 -> s1.contains(s)))
        .collect(Collectors.toSet());
    headerValues.addAll(StreamSupport.stream(values.spliterator(), false)
        .filter(Util::isNotBlank)
        .collect(Collectors.toSet()));

    // headerValues.addAll(StreamSupport.stream(values.spliterator(), false)
    // .filter(Util::isNotBlank)
    // .collect(Collectors.toSet()));
    return create(headerTemplate.getName(), headerValues);
  }
```
If you think it needs to be done this way, i can commit this code

**Comment by kdavisk6** [comment]
Your issue is related to how Spring Cloud managing the Content Type based on their annotations, not in how Feign Core handles headers.  It is acceptable to have multiple values for a given header so the implementation in `RequestTemplate` must account for that.  However, when dealing with `Content-Type`, we delegate that responsibility to the `Contract` and `Client`.

In your situation, Spring is adding the `Content-Type` header through your use of their `RequestMapping` annotation, which is managing the content type in the handling of the `MultipartFile` parameter you are providing.  In addition, the Multipart handler Spring is using, provided by Feign Form, is also processing the `Content-Type`.  My suggestion is to open this issue with the Spring Cloud team first, letting them determine if it is something they need to address in their `Contract`, or if the bug really exists in Feign Form.

Here is the related code in Feign Form:

https://github.com/OpenFeign/feign-form/blob/72ed933249eb089e4123167e4b88722c08cd8418/feign-form/src/main/java/feign/form/MultipartFormContentProcessor.java#L88-L89

**Comment by SirMin** [comment]
thanks
