### ISSUE TITLE
Body contains % ,  as JSON, UriUtils.decode error 

### ISSUE THREAD

**Issue by lee123lee123** [OpenFeign/feign#916]
Request Body
`{
      "percent" : "100%",
      "name" : "lee"
}`

Feign client  declarative invocation will decode throw exception
 URLDecoder.decode() code `throw new IllegalArgumentException(
                                   "URLDecoder: Illegal hex characters in escape "
                                            + "(%) pattern - negative value");`

UriUtils.decode()  should be contain IllegalArgumentException,  return the original value .

**Comment by kdavisk6** [comment]
Can you please provide a test case for this?  Data provided either through the `@BodyTemplate` or `@Body` annotations are not encoded.

**Comment by lee123lee123** [comment]
Data provided either through the @Body annotations are not encoded.
`    core/src/test/java/feign/TargetTest.java `

**Comment by kdavisk6** [comment]
That’s intentional. @Body values are sent in the Request Body and are not encoded.  Only @Param values placed on the uri are encoded.

**Comment by lee123lee123** [comment]
@Body values are not encoded. But BodyTemplate.expand(Map<String, ?> variables) method will decode @Body values.

**Comment by lee123lee123** [comment]
> That’s intentional. @Body values are sent in the Request Body and are not encoded. Only @param values placed on the uri are encoded.

@Body values are not encoded. But BodyTemplate.expand(Map<String, ?> variables) method will decode @Body values.

**Comment by kdavisk6** [comment]
@lee123lee123 

Body Templates do not perform any encoding.  If you look at their constructor, you will see that the `EncodingOptions` flag is set to `NotRequired`.  This bypasses all calls to `UriUtils.encodeReserved`.  Looking at the PR you submitted, along with the test case provided, I think there is a small misunderstanding on how to use the `@Body` annotation.

Let's break down the test case in the PR:

```java
interface UriPostTarget {
     @RequestLine("POST /{path}")
     @Body("{body}")
     Response post(@Param("path") String path, @Param("body") String body);
}
```
First, `@Body` annotations are used to specify the request body data and `@Param` values are used to resolve templated values.  You do not need to use a `@Param` value to resolve a `@Body` annotation, you can apply the `@Body` annotation to the method parameter:

```java
interface UriPostTarget {
     @RequestLine("POST /{path}")
     Response post(@Param("path") String path, @Body String body);
}
```

Also, you can omit the `@Body` annotation completely and Feign will automatically turn the value into the request body.

```java
interface UriPostTarget {
     @RequestLine("POST /{path}")
     Response post(@Param("path") String path, String body);
}
```

---
Now, let's return to the original interface to explain what is going on and why you are experiencing this issue.

```java
interface UriPostTarget {
     @RequestLine("POST /{path}")
     @Body("{body}")
     Response post(@Param("path") String path, @Param("body") String body);
}
```
Given what we now know, calling the `post` method will do the following:

1.  Resolve `path` and update the uri
2.  Resolve `body` as a **query string parameter** and append it to the uri: <- *this is where you are encountering the encoding issue*
3.  Resolve `body` as the **request body** and add it to the request.

Why is this happening?  Because you have combined `@Param` and `@Body` incorrectly.  Replace `@Param("body")` with `@Body` and the error should subside.
