### ISSUE TITLE
FeignException contains request- or response-body

### ISSUE THREAD

**Issue by robachmann** [OpenFeign/feign#920]
While working on #912 I came across an odd behaviour: 

In `errorStatus` a `FeignException` is created with the response's body:
https://github.com/OpenFeign/feign/blob/ce662052d788bb4c35f89c8f67a75cdaf3c68c83/core/src/main/java/feign/FeignException.java#L81

In `errorReading` a `FeignException` is created with the request's body (even though the response with its body would be at hand):
https://github.com/OpenFeign/feign/blob/ce662052d788bb4c35f89c8f67a75cdaf3c68c83/core/src/main/java/feign/FeignException.java#L72 

I think it's inconsistent and confusing for the user as he or she can't rely on the same data-source for all exceptions. On the other hand, I'm not sure whether it's intentional as there are unit-tests that check this behaviour, thus changing it could also be breaking-change for users:

https://github.com/OpenFeign/feign/blob/ce662052d788bb4c35f89c8f67a75cdaf3c68c83/core/src/test/java/feign/FeignTest.java#L525

If we agree on returning the response-body, I'd gladly create a PR for it.

**Comment by kdavisk6** [comment]
It is intentional.  Feign Exception cannot depend on a Response being available when it is created or available since these exceptions can be thrown before **and** after a request.  For example, when a request times out, a `FeignException` is created and there is no response.  In order to provide additional context, we use the `Request`.  

One thing we can do to clear up this potential confusion is to update the documentation and comment to code to make this intention clearer.
