### ISSUE TITLE
Wrong request sent with comma separated values for query param

### ISSUE THREAD

**Issue by mladenbolic** [OpenFeign/feign#942]
Passing a comma separated list of ids as string e.g. "10,20,30" resolves in version `10.1.0` to
`/users?ids=10,20,30` and in version `10.2.0` to `/users?ids=10&ids=20&ids=30`.

@RequestLine("GET /users?ids={ids}")
List<User> getUsers(@Param("ids") String ids);

Couldn't find this change in the Changelog for latest release and it can break some APIs if people are not aware of this change.

**Comment by kdavisk6** [comment]
@mladenbolic 

Thank your for raising this issue.  This is due to fixes applied in #879.  

**Background**
When attempting to expand iterable values, Feign creates an internal comma delimited string with the values and then passes it on to the `Template` to be expanded.  One unfortunate side-effect of that is if a user provides a comma delimited string, Feign treats it as an `Iterable`.  A fix for this issue has been merged via #930 and will be released with version `10.2.1`

**Comment by kdavisk6** [comment]
Released in 10.2.3

**Comment by prasadpr1** [comment]
Still facing issues with even in 11.6 version
