### ISSUE TITLE
Compare  feign with retrofit

### ISSUE THREAD

**Issue by why168** [OpenFeign/feign#955]

**Comment by kdavisk6** [comment]
@why168 

We will need more information to help with this issue.

**Comment by hellboy81** [comment]
See https://github.com/OpenFeign/feign/issues/850

**Comment by cogitaria-admin** [comment]
Excellent question.  I'm looking at this and thinking it's 2020 and what the world needs is another web framework to bring it to an even 1000 choices? This problem has been solved 10,000 times, over and over again.  Then I look at the road map and one of the highlights is caching responses? Really? New framework and you did not bake in e-tags? Then you're going to rewrite the logging framework, since for some inexplicable reason you missed SL4J interface? C'mon man. REST assured I won't touch this thing with a ten foot pole.

**Comment by why168** [comment]
feign is lightweight,retrofit is Heavyweight.😃😃😃feign borrowed retrofit style.

**Comment by hellboy81** [comment]
If you want to be OK use feign every day

/thread
