### ISSUE TITLE
no place to set EncodingOptions

### ISSUE THREAD

**Issue by YaoYufeng** [OpenFeign/feign#974]
version:  10.2.3
I have a case that don't encode url when send a request.
I find there is a class called feign.template.Template.EncodingOptions, but I don't find a way to set in feign.template.QueryTemplate .
I use Feign.builder() to build a client.

**Comment by kr5ture** [comment]
I have faced the same issue. Looks like 2d761cb commit makes annotation flag `Param#encoded` unused:
* removed code ([here](https://github.com/OpenFeign/feign/commit/2d761cb6a92efc6b4a95e7092c945f47431b76cd#diff-51b176e568a2cdf4a0174d10f0979da0L319)) which prevented value from double encoding ([here](https://github.com/OpenFeign/feign/commit/2d761cb6a92efc6b4a95e7092c945f47431b76cd#diff-31aaa08ee890c87021503798d38d031fL229))
* [javadoc](https://github.com/OpenFeign/feign/commit/2d761cb6a92efc6b4a95e7092c945f47431b76cd#diff-31aaa08ee890c87021503798d38d031fR244)  explains that already encoded values will be skipped but it seems not to be true

It works when downgrade to 10.1:
```
$ git tag --contains 2d761cb
10.2.0
10.2.1
10.2.2
10.2.3
release-10.2.0
```

**Comment by kdavisk6** [comment]
@YaoYufeng and @kr5ture 

Thank you for brining this to our attention.  To help us with your issue, can you please provide the following:

* What you are trying to accomplish?  Please provide examples, if you can.
* What is the expected behavior?
* What behavior did you observe?

If at all possible, please provide a simple test case demonstrating the issue.  This goes a long way in helping us understand your issue and how best to help.

**Comment by kr5ture** [comment]
I have tried to search for repositories which name contains `java9-mod` within `java9-modularity` organization. I have used query: `https://api.github.com/search/repositories?q=java9-mod+org:java9-modularity`.

Take a look on the following [example test](https://gist.github.com/12fcd95cd0a56f568714ea4c46277aa1). The test fails when using latest version of `OpenFeign` because `github.com` returns empty list of matching repositories. It passes when `OpenFeign` is downgraded to 10.1.0 (exacly one repository is returned which is expected). As far as I have debugged, encoding of the `+` seems to be the problem (`github.com` does not treat strings separated by `+` as separate query conditions?).

```
$ curl https://api.github.com/search/repositories?q=java9-mod+org:java9-modularity | jq '.items[].name'
```
```
"java9-modularity.github.io"
```

**Comment by kr5ture** [comment]
Found another one which I don't understand. Another [test case](https://gist.github.com/kr5ture/443d9c1015d2b42b57e60f073074a48f) where I ask for repositories which name contains `feign` within `OpenFeign` organization. Test passes when using `10.1.0` but fails when using `10.2.3` with following error:
```
java.lang.AssertionError: 
Expecting:
  <["feign",
    "feign-form",
    "feign-vertx",
    "feign-opentracing",
    "feign-reactive",
    "feign-cdi",
    "feignx"]>
to contain exactly in any order:
  <["feign",
    "feign-form",
    "feign-vertx",
    "feign-reactive",
    "feign-opentracing",
    "feign-annotation-error-decoder",
    "feign-cdi",
    "feignx"]>
but could not find the following elements:
  <["feign-annotation-error-decoder"]>
```

**Comment by kdavisk6** [comment]
@YaoYufeng 

From your test cases, it appears that you are not managing the `+` symbol accordingly.  In our [documentation](https://github.com/OpenFeign/feign#undefined-vs-empty-values)

> **What about plus? +**
>
>Per the URI specification, a + sign is allowed in both the path and query segments of a URI, however, handling of the symbol on the query can be inconsistent. In some legacy systems, the + is equivalent to the a space. Feign takes the approach of modern systems, where a + symbol should not represent a space and is explicitly encoded as %2B when found on a query string.
>
>If you wish to use + as a space, then use the literal character or encode the value directly as %20

When using the GitHub api, `+` is actually `space`.  Feign will convert it to `%2B`, which is incorrect and will result in incorrect responses from the GitHub api.  To correct this in your test case, do not use `+` but instead use a space ` ` or `%20` explicitly.

This is one of the changes added during the 10.x updates, so it is reasonable to conclude that, at least in the test cases you've provided, this is the root cause of your issue.  Try using an explicit space and let us know.

**Comment by kr5ture** [comment]
You are right @kdavisk6 . Using `space` instead of `+` resolves all issues. And now I understand why. Thanks!
